name: Build and Test SecureStorage 2.0

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'legacy/secure-storage-1'

jobs:
  assemble:
    name: AssembleDebug SecureStorage 2.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug SecureStorage 2.0
        run: |
          bash ./gradlew detekt --stacktrace
          bash ./gradlew assembleDebug --stacktrace

  test:
    needs: assemble
    name: Test SecureStorage 2.0
    runs-on: macOS-latest
    strategy:
      matrix:
        api-level: [21, 22, 23, 26, 29]
        target: [default]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test SecureStorage 2.0
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest --stacktrace