name: Build SecureStorage 2.0

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'legacy/secure-storage-1'

jobs:
  assemble:
    name: AssembleDebug SecureStorage 2.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: AssembleDebug SecureStorage 2.0
        run: |
          bash ./gradlew detekt --stacktrace
          bash ./gradlew assembleDebug --stacktrace
      - name: Notify Slack
        if: success()
        uses: drilonrecica/action-slack-notify@0.0.4
        env:
          SLACK_CHANNEL: csi-builds
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://avatars1.githubusercontent.com/u/1760904?s=200&v=4?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Notify Slack
        if: failure()
        uses: drilonrecica/action-slack-notify@0.0.4
        env:
          SLACK_CHANNEL: csi-builds
          SLACK_COLOR: '#8d0000'
          SLACK_ICON: https://avatars1.githubusercontent.com/u/1760904?s=200&v=4?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}